### ISSUE TITLE
wiki.vg closure

### ISSUE THREAD

**Issue by violine1101** [carlbennett/realcraft#1]
Hi! Your wiki pages about this project, previously hosted at wiki.vg, have been [archived on the Minecraft Wiki](https://minecraft.wiki/w/Minecraft_Wiki:Projects/wiki.vg_merge/Server_List/Realcraft) following the closure of wiki.vg. Please let us know what you would like to do with them; e.g. they could be integrated into this GitHub repo, made into a user-space page on the wiki, or be deleted outright.

**Comment by bigfoot547** [comment]
Regarding merging them into this github repo, I have made #2 as an example of what that might look like. Please note that those markdown files are derived from articles on wiki.vg, and are therefore licensed under the CC BY-SA 3.0 Unported license, not the MIT license. The PR contains the license text and appropriate verbiage for the situation.

**Comment by carlbennett** [comment]
Thanks 👍🏻 for putting together the pull request to implement into this repository. I've welcomed it and merged it.

I almost forgot this project existed 😃 . It has been sometime since I worked on it. Feel free to remove the wiki.vg related pages, sorry those have been left there for so long.
